### PR TITLE
Remove viewer type and move all fields to the root query

### LINKED ISSUE #16: Move fields from viewer to root type when possible

### PR DESCRIPTION
**Pull request by jkettmann**
Closes #16

### CODE REVIEW

**Comment by jkettmann** [comment]
@MartinDawson You mentioned, that you got rid of the viewer type. I moved the posts connection here from the viewer to the [root query](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/646b76b26d0091daf0f8e1fb98ea75f6c3961b4d/server/graphql/type/QueryType.js#L19). Now I'm running into problems on the client, because I'm not sure, how to write the query. Did you solve that already? I tried following

[The components container](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/646b76b26d0091daf0f8e1fb98ea75f6c3961b4d/client/pages/Posts/Posts.js#L48)

```
fragment Posts_posts on PostConnection {
  pageInfo {
    hasNextPage
    endCursor
  },
  edges {
    node {
      id
      ...PostTeaser_post
    }
  }
}
```

and the [posts route](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/646b76b26d0091daf0f8e1fb98ea75f6c3961b4d/client/pages/Posts/PostsRoute.js#L6)

```
query PostsRoute_Query ($afterCursor: String, $count: Int!) {
  posts (after: $afterCursor first: $count) @connection(key: "Posts_posts") {
    ...Posts_posts
  }
}
```

What should I do in the [pagination query](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/646b76b26d0091daf0f8e1fb98ea75f6c3961b4d/client/pages/Posts/Posts.js#L80)? Any idea?

**Comment by jkettmann** [comment]
@MartinDawson Seems like you had the [same issue](https://github.com/facebook/relay/issues/1705#issuecomment-340220976) :-)

**Comment by MartinDawson** [comment]
Yeah, just move your `connection` directive to the fragment. My Example: https://github.com/MartinDawson/SoundVast/blob/graphql/src/SoundVast/wwwroot/components/songs/songsContainer.jsx

Btw, I'm on slack from home so I can give faster responses if you message me there if you want.

**Comment by jkettmann** [comment]
@MartinDawson Thanks a lot. It worked. It"s funny though, that you explicitly have to pass the data object inside the render function [like here](https://github.com/jkettmann/universal-react-relay-starter-kit/blob/ddc0c3e475009031705511af6cb11031a4d1125b/client/Router/routeConfig.js#L46). Didn't need to do that before

**Pull request merged**
